### ISSUE TITLE
Charts & Tables, typo in Notes column for FLN Strike activity

### ISSUE THREAD

**Issue by rummelsworth** [rally-the-troops/algeria#1]
![image](https://github.com/rally-the-troops/algeria/assets/3069355/0b9e326c-860b-4d42-8f5c-3e5f14c03e7d)

The 3rd bullet says "Penality". Probably meant to say "Penalty".

**Comment by MischaU8** [comment]
Typos fixed, thanks for reporting! (file will be updated in next deployment)
